# code from http://stackoverflow.com/questions/4332478/read-the-current-text-color-in-a-xterm/4332530#4332530
NORMAL    = $$(tput sgr0)
REVERSE   = $$(tput smso)
BLACK     = $$(tput setaf 0)
RED       = $$(tput setaf 1)
GREEN     = $$(tput setaf 2)
YELLOW    = $$(tput setaf 3)
BLUE      = $$(tput setaf 4)
MAGENTA   = $$(tput setaf 5)
CYAN      = $$(tput setaf 6)
WHITE     = $$(tput setaf 7)
BRIGHT    = $$(tput bold)
NORMAL    = $$(tput sgr0)
BLINK     = $$(tput blink)
REVERSE   = $$(tput smso)
UNDERLINE = $$(tput smul)
