
TARGETS=libemu_core libemu_mips

include ../config.mk
include ../build.mk/targets.mk



#all:
#    @for target in $(TARGETS); do @printf "$(CYAN)$(BRIGHT)\n\n   build target: $${target}\n\n$(NORMAL)"; make -C $${target}; done

#install:
#    @for target in $(TARGETS); do @printf "$(CYAN)$(BRIGHT)\n\n   install target: $${target}\n\n$(NORMAL)"; make -C $${target} install; done
#
#clean:
#    @for target in $(TARGETS); do @printf "$(CYAN)$(BRIGHT)\n\n   clean target: $${target}\n\n$(NORMAL)"; make -C $${target} clean; done

